remote_theme: chrisrhymes/bulma-clean-theme@v0.14.0
title: 4G Buitengebied

theme_color: '#159957'

fixed_navbar: top
footer_menu: footer-menu

paginate: 5
paginate_path: "/blog/page:num"

google_analytics: UA-64468549-34

permalink: pretty

plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag
  - kramdown-parser-gfm

exclude:
  - Gemfile
  - clean-theme.gemspec
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

sass:
  style: compressed
  source_dir: _sass

markdown: kramdown
highlighter: rouge

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      hero_image: /assets/images/koeien.jpg
      show_sidebar: true
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post
      show_sidebar: true
